STAJJ/cal/urls.py
# vary from tutorial because it used outdated django
from django.urls import re_path
from . import views

app_name = 'cal'

urlpatterns = [
        re_path(r'^personalcal/listview/$', views.PersonalListView.as_view(), name='cockycal-personallist'),
    re_path(r'^eventcal/$', views.EventCalendarView.as_view(), name='cockycal-eventcal'),
    re_path(r'^personalcal/$', views.PersonalCalendarView.as_view(), name='cockycal-personalcal'),
    re_path(r'^eventcal/event/new/$', views.event, name='event_new'),
    re_path(r'^personalcal/event/new/$', views.pers_event, name='personal_event_new'),
    re_path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    re_path(r'^personalevent/edit/(?P<event_id>\d+)/$', views.pers_event, name='personal_event_edit'),
    re_path(r'^eventcal/event/details/(?P<event_id>\d+)/$', views.event_details, name='event_details'),
    re_path(r'^eventcal/event/added/(?P<event_id>\d+)/$', views.event_details, name='added_event'),
    re_path(r'^eventcal/listview/$', views.EventListView.as_view(), name='cockycal-eventlist'),
    re_path(r'^personalcal/event/details/(?P<event_id>\d+)/$', views.personal_event_details, name='personal_event_details'),
    re_path(r'^personalcal/event/added/(?P<event_id>\d+)/$', views.personal_event_details, name='personal_added_event'),
]

STAJJ/stajj2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", user_views.register, name = "register"),
    
    path('', include('users.urls')),
    path('', include('mainpage.urls')),
    path('', include('cockycal.urls')),
    path('', include('cal.urls')),

]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

STAJJ/cal/models.py
#code influenced from github tutorial for implementing a calendar 
# github found at https://github.com/huiwenhw/django-calendar
#additions and changes were made to that code to suit needs of our project

#filter documentation at https://django-filter.readthedocs.io/en/stable/guide/usage.html#the-model

# Create your models here.
from django.db import models

from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

class Event(models.Model):
    hide = models.BooleanField(default=False)
    title = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location = models.TextField(
        default = "University of South Carolina"
    )
    description = models.TextField(
        default = "User Added Event"
    )
    personal_event = models.BooleanField(
        default = False
    )
    posting_User_email = models.TextField(default="Web Scraped")
    TAGS = (
        ('UofSC Event','UofSC Event'),
        ('Columbia Event', 'Columbia Event'),
        ('Athletic Event','Athletic Event'),
        ('Club Event', 'Club Event'),
        ('Miscellaneous', 'Miscellaneous'),
    )
    filterTag = models.TextField(
        choices = TAGS,
        default = 'None'
    )
    
    @property
    def get_html_url(self):
        current_tz = timezone.get_current_timezone()
        url = reverse('cal:event_details', args=(self.id,))
        return f'<a href="{url}"> {self.title} {self.start_time.astimezone(current_tz).strftime("%H:%M")}</a>'

    @property
    def get_personal_html_url(self):
        current_tz = timezone.get_current_timezone()
        url = reverse('cal:personal_event_details', args=(self.id,))
        return f'<a href="{url}"> {self.title} {self.start_time.astimezone(current_tz).strftime("%H:%M")}</a>'
    
    @property
    def get_edit_html_url(self):
        current_tz = timezone.get_current_timezone()
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} {self.start_time.astimezone(current_tz).strftime("%H:%M")}</a>'

    @property
    def get_personal_edit_html_url(self):
        current_tz = timezone.get_current_timezone()
        url = reverse('cal:personal_event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} {self.start_time.astimezone(current_tz).strftime("%H:%M")}</a>'

    @property
    def get_list_url(self):
        url = reverse('cal:event_details', args=(self.id,))
        return f'<a href="{url}"> {self.title}</a>'

    @property
    def get_personal_list_url(self):
        url = reverse('cal:personal_event_details', args=(self.id,))
        return f'<a href="{url}"> {self.title}</a>'

    @property
    def get_edit_list_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title}</a>'
    
    @property
    def get_personal_edit_list_url(self):
        url = reverse('cal:personal_event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title}</a>'
    
    @property
    def valid_url(self):
        validate_url = URLValidator()  
        try:
            validate_url(self.description)
        except (ValidationError):
            return self.description 
        return f'<a href="{ self.description }">Click for More Information</a>'

STAJJ/cal/forms.py
# using tutorial, github found at https://github.com/huiwenhw/django-calendar

from django.forms import ModelForm, DateInput
from cal.models import Event

from django import forms 


class EventForm(forms.ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = ["title", "location","description", "start_time", "end_time", "filterTag",]

  def clean(self):
    # data from the form is fetched using super function
    super(EventForm, self).clean()
      
    start_time = self.cleaned_data.get('start_time')
    end_time = self.cleaned_data.get('end_time')
    if start_time > end_time:
      raise forms.ValidationError('End time must occur after Start time')
    return self.cleaned_data

        

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)
  
  def save(self, commit=True):
    m = super(EventForm, self).save(commit=False)
    # do custom stuff
    m.title = m.title.replace("<"," ").replace(">"," ")
    m.location = m.location.replace("<","").replace(">"," ")
    m.description = m.description.replace("<","").replace(">"," ")
    if commit:
        m.save()
    return m

STAJJ/cal/views.py
# using tutorial at https://github.com/huiwenhw/django-calendar


# Create your views here.

from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .utils import EventCalendar, PersonalCalendar, EventList, PersonalList
from .filter import EventFilter
from .models import Event
from .forms import EventForm
from users.models import CustomUser
from cockycal.models import TaskItem
from django.contrib.auth.decorators import login_required

from users.utils import add_event_to_user, remove_event_from_user
from django.contrib.auth.mixins import LoginRequiredMixin

#Class to generate views for the Event Calendar

class EventCalendarView(LoginRequiredMixin,generic.ListView):
    login_url = 'login'
    model = Event
    template_name = 'cal/eventcalendar.html'

    #Upon request returns data for the view as elements of a context list that are called in cal/eventcalendar.html
    def get_context_data(self, **kwargs):
        date = get_date(self.request.GET.get('month', None))

        context = super().get_context_data(**kwargs)
        events = Event.objects.all().order_by('start_time')

        filtered_events, eventfilter = apply_filter(events, self.request.GET)
        user = self.request.user

        cal = EventCalendar(events, date.year, date.month)
        html_cal = cal.formatmonth(user, eventlist=filtered_events, withyear=True)
        legend = cal.legend()
        context['prev_month'] = prev_month(date)
        context['next_month'] = next_month(date)
        #creates context for the from the string created in EventCalendar formatmonth from Utils using Mark Safe
        context['eventcalendar'] = mark_safe(html_cal)
        context['eventfilter'] = eventfilter.form
        context['month'] = str(date.year) + '-' + str(date.month)
        context['legend'] = mark_safe(legend)
        #get applied filter to pass through get request if filter is not empty
        try: 
            context['filterParams'] = "&title="+self.request.GET.get('title') + "&" + "location="+self.request.GET.get('location') + "&" + "filterTag="+self.request.GET.get('filterTag')
        except:
            context['filterParams'] = ""
        return context


class PersonalCalendarView(LoginRequiredMixin,generic.ListView):
    login_url = 'login'
    model = Event
    template_name = 'cal/personalcalendar.html'

    #Upon request returns data for the view as elements of a context list that are called in cal/personalcalendar.html
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date = get_date(self.request.GET.get('month', None))
        cal = PersonalCalendar(date.year, date.month)
        user = self.request.user
        try:
            events = user.events_attending.all().order_by('start_time')
        except:
            events = Event.objects.all().filter(title="Not a Real Event")
        filtered_events, eventfilter = apply_filter(events, self.request.GET)
        cal = PersonalCalendar(events, date.year, date.month)
        task_list = TaskItem.objects.filter(author=user)
        html_cal = cal.formatmonth(user, events=filtered_events, tasks_list=task_list, withyear=True)
        legend = cal.legend()
        #creates context for the from the string created in PersonalCalendar formatmonth from Utils using Mark Safe
        context['personalcalendar'] = mark_safe(html_cal)
        context['eventfilter'] = eventfilter.form
        context['prev_month'] = prev_month(date)
        context['next_month'] = next_month(date)
        context['legend'] = mark_safe(legend)
        try: 
            context['filterParams'] = "&title="+self.request.GET.get('title') + "&" + "location="+self.request.GET.get('location') + "&" + "filterTag="+self.request.GET.get('filterTag')
        except:
            context['filterParams'] = ""
        context['month'] = str(date.year) + '-' + str(date.month)
        
        return context

#If passed a month, it returns a date in the month, otherwise returns the current date 
def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

#Logic for previous month button returns month prior to month passed to it 
def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

#Logic for next month button returns month after the month passed to it 
def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

#View for creating a new event and posting to the event calendar
def event(request, event_id=None):
    #creates an instance of an event
    instance = Event()
    #if event already exists it returns the data for that object, otherwise creates new event
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
        instance.posting_User_email = request.user.email
        form = EventForm(request.POST or None, instance=instance)
        if request.POST and form.is_valid():
            form.save()
            add_event_to_user(request,instance.pk)
            return HttpResponseRedirect(reverse('cal:cockycal-eventcal'))
        return render(request, 'cal/event.html', {'form': form})
    #adds event to the list of event calendar events
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and 'Delete' in request.POST:
            instance.delete()
            return HttpResponseRedirect(reverse('cal:cockycal-eventcal'))
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:cockycal-eventcal'))
    if request.user.email == instance.posting_User_email:
        return render(request, 'cal/edit_event.html', {'form': form})
    return render(request, 'cal/event.html', {'form': form})

#View for creating a new event and posting to personal calendar
def pers_event(request, event_id=None):
    #creates an instance of an event
    instance = Event()
    #if event already exists it returns the data for that object, otherwise creates new event
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
        instance.personal_event = True
        instance.posting_User_email = request.user.email
        form = EventForm(request.POST or None, instance=instance)
        if request.POST and form.is_valid():
            form.save()
            add_event_to_user(request,instance.pk)
            return HttpResponseRedirect(reverse('cal:cockycal-personalcal'))
        return render(request, 'cal/event.html', {'form': form})
        
    #adds event to the list of event calendar events
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and 'Delete' in request.POST:
            instance.delete()
            return HttpResponseRedirect(reverse('cal:cockycal-personalcal'))
    if request.POST and form.is_valid():
        form.save()
        add_event_to_user(request,instance.pk)
        if 'Delete' in request.POST:
            instance.delete() 
        return HttpResponseRedirect(reverse('cal:cockycal-personalcal'))
    if request.user.email == instance.posting_User_email:
        return render(request, 'cal/personal_edit_event.html', {'form': form})
    return render(request, 'cal/event.html', {'form': form})

#View for the details page when an event is clicked on
def event_details(request, event_id):
    #gets instance of event or throws forbidden error
    event = get_object_or_404(Event,pk=event_id)
    validated_url = event.valid_url
    #gets the current user
    user = request.user
    #Shows Remove event button if user has event on personal calendar
    if event in user.events_attending.all():
        if 'Remove' in request.POST:
            remove_event_from_user(request, event_id)
            return render(request, 'cal/event_details.html',{'event':event,'valid_url':mark_safe(validated_url)})
        return render(request, 'cal/added_event.html',{'event':event, 'valid_url':mark_safe(validated_url)})
    #Shows add event button if user does not have event on personal calendar
    if 'Add' in request.POST:
        add_event_to_user(request,event_id)
        return render(request, 'cal/added_event.html',{'event':event, 'valid_url':mark_safe(validated_url)})
    return render(request, 'cal/event_details.html',{'event':event, 'valid_url':mark_safe(validated_url)})

#View for the details page when an event is clicked on
def personal_event_details(request, event_id):
    #gets instance of event or throws forbidden error
    event = get_object_or_404(Event,pk=event_id)
    #gets the current user
    user = request.user
    validated_url = event.valid_url
    #Shows Remove event button if user has event on personal calendar
    if event in user.events_attending.all():
        if 'Remove' in request.POST:
            remove_event_from_user(request, event_id)
            return render(request, 'cal/personal_event_details.html',{'event':event, 'valid_url':mark_safe(validated_url)})
    #Shows add event button if user does not have event on personal calendar
    if 'Add' in request.POST:
        add_event_to_user(request,event_id)
        return render(request, 'cal/personal_added_event.html',{'event':event, 'valid_url':mark_safe(validated_url)})
    return render(request, 'cal/personal_added_event.html',{'event':event, 'valid_url':mark_safe(validated_url)})

STAJJ/cal/templates/cal/added_event.html
<!--This html page displays event details for events that are added to a Users personal Calendar and redirects to the Event Calendar-->
{% extends 'cal/base.html' %}

{% block content %}
<h1>{{ event.title }}</h1>
<style>
  .btn {
    background-color: #73000a;
  }
.btn:hover {
    background-color:#000000;
    transition: 0.3s;
}
</style>

<p class="eventinfo">{{ event.location }}</p>
<p class="eventinfo">Begins at {{ event.start_time}}</p>
<p class="eventinfo">Ends at {{ event.end_time}}</p>
<p class="eventinfo">{{ event.filterTag}}</p>
<p class="eventinfo">{{ valid_url }}</p>
<p class="eventinfo">This event is currently added to your personal calendar!</p>


<div class="clearfix">
    <a class="btn btn-info right" href="/eventcal/listview"> Return to List View </a>
    <a class="btn btn-info right" href="/eventcal"> Return to Calendar View </a>
    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
          <tr><td colspan="0"><button type="submit" name="Remove" class="btn btn-info left">Remove from Personal Calendar</button></td></tr>
        </table>
        
    </form>
</div>

{% endblock %}

STAJJ/cal/templates/cal/base.html
<!--using tutorial at https://github.com/huiwenhw/django-calendar-->

{% if user.is_authenticated%}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
   <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}?version=55">
   <link rel="stylesheet" type="text/css" href="{% static 'mainpage/menu.css' %}?version=55">
    <title>Event Calendar</title>

      
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static 'cockycal/main.css' %}?version=55">
  
      {% if title %}
          <title>Cocky Calendar - {{ title }}</title>
      {% else %}
          <title>Cocky Calendar</title>
      {% endif %}
  </head>

    <style>
      body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
    
      body, html {
        height: 100%;
        line-height: 1.8;
      }
      
      /* Full height image header */
      .bgimg-1 {
        background-position: center;
        background-size: cover;
        background-image: url("https://th.bing.com/th/id/OIP.RjvhnkdJLD5tNuoJSSsWOwHaEe?w=299&h=181&c=7&r=0&o=5&dpr=2&pid=1.7");
        min-height: 100%;
      }
      
      .w3-bar .w3-button {
        padding: 16px;
      }
    
    
    </style>
  <body>
    
    <!-- Navbar (sit on top) -->
    <div class="w3-top">
      <div class="w3-bar w3-card" style= "background-color:#73000A" id="myNavbar">
        <a href="/" class="w3-bar-item w3-button w3-wide" style= "color:#bbbbbb">Cocky Calendar</a>
        {% if user.is_authenticated %}
        <a href="/home" onclick="w3_close()" class="w3-bar-item w3-button w3-wide"style= "color:#bbbbbb">Home</a>
        {% endif %}
        <!-- Right-sided navbar links -->
        <div class="w3-right w3-hide-small">
          {% if user.is_authenticated %}
          <a href="/eventcal" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-bullhorn"></i> Event Cal</a>
          <a href="/personalcal" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-calendar"></i> Personal Cal</a>
          <a href="/tasklist" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-list-ul"></i> Task List</a>
          <a href="/profile" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-user"></i> Profile</a>
          <a href= "/logout" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-sign-out"></i> Logout</a>
          {% else %}
          <a href="/login" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-user"></i> Login</a>
          <a href="/register" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-user-plus"></i> Register</a>
          {% endif %}
          
          
          
        </div>
        <!-- Hide right-floated links on small screens and replace them with a menu icon -->
    
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div>
    
    <!-- Sidebar on small screens when clicking the menu icon -->
    <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="mySidebar">
      <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
      {% if user.is_authenticated %}
      <a href="/home" onclick="w3_close()" class="w3-bar-item w3-button">Home</a>
      <a href="/logout" onclick="w3_close()" class="w3-bar-item w3-button">Logout</a>
      {% else %}
      <a href="/login" onclick="w3_close()" class="w3-bar-item w3-button">Login</a>
      <a href="/register" onclick="w3_close()" class="w3-bar-item w3-button">Register</a>
      {% endif%}
      <a href="/eventcal" onclick="w3_close()" class="w3-bar-item w3-button">Event Calendar</a>
      <a href="/personalcal" onclick="w3_close()" class="w3-bar-item w3-button"> Personal Calendar</a>
      <a href="/tasklist" onclick="w3_close()" class="w3-bar-item w3-button">Task List</a>
      <a href="/profile" onclick="w3_close()" class="w3-bar-item w3-button">Profile</a>
    </nav>
    
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
                <div class = "alert alert-{{ message.tags }}"> 
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          </div>
        </div>
      </main>
  <br>
  <br>
  <h1 class="title pl-2">{% block title %} {% endblock %}</h1>
  <hr>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
{%endif%}

</html>

STAJJ/cal/templates/cal/edit_event.html
<!--This html page displays a page for editting event calendar events for the user that posted them-->
{% extends 'cal/base.html' %}

{% block title %}
Edit Your Event
{% endblock %}

{% block content %}
<style>
  .btn {
    background-color: #73000a;
  }
.btn:hover {
    background-color:#000000;
    transition: 0.3s;
}
</style>
<div class="clearfix">
  <a class="btn btn-info left" href="/eventcal"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="0"><button type="submit" name="Delete" class="btn btn-info left">Delete Event</button></td></tr>
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

STAJJ/cal/templates/cal/eventlist.html
<!--This html page displays the Event Calendar in a list view-->
{% extends 'cal/base.html' %}
{% block title %}
Event List
{% endblock %}

{% block content %}
<style>
    .btn {
      background-color: #73000a;
    }
	.btn:hover {
      background-color:#000000;
      transition: 0.3s;
  }
</style>
<form method="get" class="eventfilter">
	{{ eventfilter }}

	<button class="btn btn-primary" type="submit">
		Search
	</button>
	
</form>

<div class="clearfix">
	<form id="add_remove_event" method="get" action="{% url 'cal:cockycal-eventlist' %}">
		{% csrf_token %}
		<a class="btn btn-info left" href="/eventcal/event/new"> Create Event </a>
		<button class="btn btn-info right" name="add_remove" type="submit"> Add/Remove Selected Events</button>
		<a class="btn btn-info right" href="/eventcal"> Calendar View </a>
		<br><br>
		{{ eventlist }}        
	</form>
</div>


{% endblock %}

STAJJ/cal/templates/cal/personallist.html
<!--This html page displays event details the Personal Calendar Listview-->
{% extends 'cal/base.html' %}

{% block title %}
Personal Event List
{% endblock %}

{% block content %}
<style>
    .btn {
      background-color: #73000a;
    }
	.btn:hover {
      background-color:#000000;
      transition: 0.3s;
  }
</style>
<form method="get" class="eventfilter">
	{{ eventfilter }}

	<button class="btn btn-primary" type="submit">
		Search
	</button>
</form>

<div class="clearfix">
	<form id="remove_event" method="get" action="{% url 'cal:cockycal-personallist' %}">
		{% csrf_token %}
		<a class="btn btn-info left" href="/personalcal/event/new"> Create Event </a>
		<button class="btn btn-info right" name="Remove" type="submit"> Remove Selected Events</button>
		<a class="btn btn-info right" href="/personalcal"> Calendar View </a>
		<br><br>
		{{ personallist }}           
	</form>
</div>


{% endblock %}