STAJJ/cal/urls.py
# vary from tutorial because it used outdated django
from django.urls import re_path
from . import views

app_name = 'cal'

urlpatterns = [
        re_path(r'^personalcal/listview/$', views.PersonalListView.as_view(), name='cockycal-personallist'),
    re_path(r'^eventcal/$', views.EventCalendarView.as_view(), name='cockycal-eventcal'),
    re_path(r'^personalcal/$', views.PersonalCalendarView.as_view(), name='cockycal-personalcal'),
    re_path(r'^eventcal/event/new/$', views.event, name='event_new'),
    re_path(r'^personalcal/event/new/$', views.pers_event, name='personal_event_new'),
    re_path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    re_path(r'^personalevent/edit/(?P<event_id>\d+)/$', views.pers_event, name='personal_event_edit'),
    re_path(r'^eventcal/event/details/(?P<event_id>\d+)/$', views.event_details, name='event_details'),
    re_path(r'^eventcal/event/added/(?P<event_id>\d+)/$', views.event_details, name='added_event'),
    re_path(r'^eventcal/listview/$', views.EventListView.as_view(), name='cockycal-eventlist'),
    re_path(r'^personalcal/event/details/(?P<event_id>\d+)/$', views.personal_event_details, name='personal_event_details'),
    re_path(r'^personalcal/event/added/(?P<event_id>\d+)/$', views.personal_event_details, name='personal_added_event'),
]

STAJJ/cockycal/urls.py
from django.urls import include, path
from . import views
from users import views as user_views
from django import forms

urlpatterns = [
    path("login/", views.login, name ='login'),
    path("home/", views.home, name='cockycal-home'),
    path("profile/", views.profile, name='cockycal-profile'),
    path("tasklist/", views.ItemListView.as_view(), name='cockycal-tasklist'),
    path("login/", views.login, name ="cockycal-login"),
    # CRUD patterns for ToDoItems
    path(
        "tasklist/item/add/",
        views.ItemCreate.as_view(),
        name="item-add",
    ),
    path(
        "tasklist/item/<int:pk>/",
        views.ItemUpdate.as_view(),
        name="item-update",
    ),
    path(
        "tasklist/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item-delete",
    ),
    path("cal/",include('cal.urls',namespace='details')),
]

STAJJ/stajj2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", user_views.register, name = "register"),
    
    path('', include('users.urls')),
    path('', include('mainpage.urls')),
    path('', include('cockycal.urls')),
    path('', include('cal.urls')),

]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

STAJJ/cockycal/models.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser
from django.urls import reverse
from django_resized import ResizedImageField

#https://www.youtube.com/watch?v=q4jPR-M0TAQ&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=6 
# used this tutorial to set up my user registration system-->
# Create your models here.
def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)

# Profile Models
class Image(models.Model):
    title = models.CharField(max_length=200)
    image = ResizedImageField(size=[500, 500],null=True, blank=True, upload_to="images/")
    
    def clean_image(self):
        image_field = self.cleaned_data.get('image')
        if image_field:
            try:
                image_file = BytesIO(image_field.file.read())
                image = Image.open(image_file)
                image.thumbnail((300, 300), Image.ANTIALIAS)
                image_file = BytesIO()
                image.save(image_file, 'PNG')
                image_field.file = image_file
                image_field.image = image

                return image_field
            except IOError:
                logger.exception("Error during resize image")

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class TaskItem(models.Model):
    LISTS = (
        ('General Tasks','General Tasks'),
        ('Priority Tasks','Priority Tasks'),
        ('Class Tasks','Class Tasks'),
        ('Misc. Tasks','Misc. Tasks'),
    )
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    task_list = models.CharField(max_length=100,choices=LISTS)
    # Jack LOOK HERE: this adds the author field
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse(
            "item-update", args=[str(self.task_list.id), str(self.id)]
        )
    def get_calendar_url(self):
        url = reverse(
            "item-update", args=[str(self.task_list.id), str(self.id)]
        )
        return f'<a href="{url}"> {self.title}</a>'

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        ordering = ["due_date"]

STAJJ/cockycal/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, DateInput
from .models import Image, TaskItem
from cockycal.models import Image 
from users.models import Profile
from users.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, EditProfileForm

#form that handles images 
class ImageForm(forms.ModelForm):
    image = forms.ImageField(
        widget=forms.FileInput(
        attrs={
            "class": "form-control"
        }
    ))
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    class Meta:
        model = Image
        fields = ('title', 'image','x', 'y', 'width', 'height',)
        labels = {'user_image': ''},
        
    def save(self):
        photo = super(ImageForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.image)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.image.path)

        return photo
    #cleans the image to resize 
    def clean_image(self):
        image_field = self.cleaned_data.get('image')
        if image_field:
            try:
                image_file = BytesIO(image_field.file.read())
                image = Image.open(image_file)
                image.thumbnail((300, 300), Image.ANTIALIAS)
                image_file = BytesIO()
                image.save(image_file, 'PNG')
                image_field.file = image_file
                image_field.image = image

                return image_field
            except IOError:
                logger.exception("Error during resize image")
#update the profile image on profile page   
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        
class ItemForm(ModelForm):
  class Meta:
    model = TaskItem
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'due_date': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = ["task_list", "title", "description", "due_date","completed"]

  def __init__(self, *args, **kwargs):
    super(ItemForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['due_date'].input_formats = ('%Y-%m-%dT%H:%M',)
    
  def save(self,commit=True):
    m = super(ItemForm, self).save(commit=False)
    # do custom stuff
    m.title = m.title.replace("<"," ").replace(">"," ")
    m.description = m.description.replace("<","").replace(">"," ")
    if commit:
        m.save()
    return m
#form to edit info in profile 
class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name','occupation','birthday','phonenumber']

        



        

STAJJ/cockycal/views.py
from pyexpat.errors import messages
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from django import forms 
from django.views import generic
from .forms import ImageForm, ItemForm
from .models import TaskItem
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.template.response import TemplateResponse
from datetime import datetime
import csv
import requests
from cal.models import Event
from cal.utils import EventList
from django.utils import timezone
from django.utils.safestring import mark_safe
from users.utils import upcoming_events, weekly_events, upcoming_tasks
from users.views import profile
from users.forms import UserCreationForm, UserRegisterForm, ProfileUpdateForm
from users.models import Profile, CustomUser
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta, date
from cal.utils import EventCalendar
from cal.models import Event
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

@login_required (login_url='login')
def home(request):
    api_key = 'fa321620cd169c7e6b9d92c2786d4cce'
    url = f'https://api.openweathermap.org/data/2.5/forecast/daily?q=Columbia,South Carolina&cnt=7&appid={api_key}&units=imperial'
    weather_data = None
    result = requests.get(url).json()
    user = CustomUser.objects.get(pk=request.user.pk)
    if "city" in result:
        weather_forecast = []
        for i,item in enumerate(result['list']):
            weather_data = {
                'date': datetime.fromtimestamp(item['dt']).strftime("%m-%d-%Y"),
                'temp_high': item['temp']['max'],
                'temp_low': item['temp']['min'],
                'description': item['weather'][0]['description'],
                'icon': item['weather'][0]['icon'],
            }
            weather_forecast.append(weather_data)
    upcoming = upcoming_events(user)
    tasks = upcoming_tasks(user)
    if request.method == 'POST':
        if request.POST.getlist('delete_event') is not None:
            event_ids = request.POST.getlist('delete_event')
            for event in user.events_attending.all():  
                if str(event.pk) in event_ids:
                    user.events_attending.remove(event)
                    user.upcoming_events.remove(event)
                    event.hide = True
                    event.save()                    
                    user.save()
        elif request.POST.getlist('task_completed') is not None:
            task_complete = request.POST.getlist('task_completed')
            for task in task_complete:
                comp_task = TaskItem.objects.filter(pk=task)
                for instance in comp_task:
                    instance.completed = True
                    instance.save()
        return redirect('/home')
    context = {'weather_forecast': weather_forecast,
              'upcoming': upcoming,
              'tasks' : tasks
              }
    return TemplateResponse(request, 'cockycal/home.html', context)
    
def eventcal(request):
    return render(request, 'cockycal/eventcal.html')

def personalcal(request):
    return render(request, 'cockycal/personalcal.html')

@login_required (login_url='login')
def tasklist(request):
    return render(request, 'cockycal/tasklist.html')

def signup(request):
    return render(request, 'accounts/signup.html')

def register(request):
    return render(request, 'users/register.html')

def login(request):
    return render(request, 'users/login.html')

@login_required (login_url='login')
def profile(request):
    user = CustomUser.objects.get(pk=request.user.pk)

    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            #return redirect('cockycal/profile.html')
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)
    weekly = weekly_events(user)
    context = {
        'p_form':p_form, 
        'weekly':weekly,
    }
    return TemplateResponse(request, 'cockycal/profile.html', context)

# This creates the list of tasks for each category 
class ItemListView(LoginRequiredMixin,ListView):
    login_url = 'login'
    model = TaskItem
    template_name = "cockycal/tasklist.html"

    def get_queryset(self):
        # This filters the queryset to only display the user's tasks
        user = CustomUser.objects.get(pk=self.request.user.pk)
        return TaskItem.objects.filter(author=user)
    
    def get_context_data(self):
        context = super().get_context_data()
        context["general_tasks"] = TaskItem.objects.filter(task_list='General Tasks').filter(author=self.request.user)
        context["pri_tasks"] = TaskItem.objects.filter(task_list='Priority Tasks').filter(author=self.request.user)
        context["class_tasks"] = TaskItem.objects.filter(task_list='Class Tasks').filter(author=self.request.user)
        context["misc_tasks"] = TaskItem.objects.filter(task_list='Misc. Tasks').filter(author=self.request.user)
        return context

# Creating a new item to be added to the task list
class ItemCreate(LoginRequiredMixin,CreateView):
    model = TaskItem
    form_class = ItemForm
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.is_valid()
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return kwargs

    def get_context_data(self):
        context = super(ItemCreate, self).get_context_data()
        context["title"] = "Create A New Task"
        return context
    
    def get_success_url(self):
        return reverse_lazy('cockycal-tasklist')

# Updating an item in the existing task list
class ItemUpdate(LoginRequiredMixin,UpdateView):
    model = TaskItem
    form_class = ItemForm
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.is_valid()
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return kwargs

    def get_context_data(self):
        context = super(ItemUpdate, self).get_context_data()
        context["task_list"] = self.object.task_list
        context["title"] = "Edit Task"
        return context

    def get_success_url(self):
        return reverse_lazy('cockycal-tasklist')

# Deleting an item in the task list
class ItemDelete(LoginRequiredMixin,DeleteView):
    model = TaskItem
    login_url = 'login'

    def get_success_url(self):
        return reverse_lazy('cockycal-tasklist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["task_list"] = self.object.task_list
        return context
    
def edit_profile(request):
    if request.method == "POST":
        e_form = EditProfileForm(request.POST,instance=request.user.profile)
        if e_form.is_valid():
            name=  e_form.cleaned_data["name"]
            occupation =  e_form.cleaned_data["occupation"]
            birthday =  e_form.cleaned_data["birthday"]
            phonenumber = e_form.cleaned_data["phonenumber"]
            
            user.profile.save()
            e_form.save()
    else:
        e_form = EditProfileForm()
    return render(request, 'profile.html', {'e_form': e_form})

STAJJ/cockycal/templates/cockycal/base.html
<!-- https://www.youtube.com/watch?v=qDwdMDQ8oX4&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=3 -->
 <!-- used this tutorial for templating  -->


<!DOCTYPE html>
<html>
  <head>
  <title>Cocky Calendar</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css" rel="stylesheet" />

    {% if title %}
        <title>Cocky Calendar - {{ title }}</title>
    {% else %}
        <title>Cocky Calendar</title>
    {% endif %}
  <style>
  body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
  
  body, html {
    height: 100%;
    line-height: 1.8;
  }
  
  /* Full height image header */
  .bgimg-1 {
    background-position: center;
    background-size: cover;
    background-image: url("https://th.bing.com/th/id/OIP.RjvhnkdJLD5tNuoJSSsWOwHaEe?w=299&h=181&c=7&r=0&o=5&dpr=2&pid=1.7");
    min-height: 100%;
  }
  
  .w3-bar .w3-button {
    padding: 16px;
  }
  
  
  </style>
  </head>
  <body>
  
  <!-- Navbar (sit on top) -->
  <div class="w3-top">
    <div class="w3-bar w3-card" style= "background-color:#73000A" id="myNavbar">
      <a href="/" class="w3-bar-item w3-button w3-wide" style= "color:#bbbbbb">Cocky Calendar</a>
      {% if user.is_authenticated %}
      <a href="/home" onclick="w3_close()" class="w3-bar-item w3-button w3-wide"style= "color:#bbbbbb">Home</a>
      {% endif %}
      <!-- Right-sided navbar links -->
      <div class="w3-right w3-hide-small">
        {% if user.is_authenticated %}
        <a href="/eventcal" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-bullhorn"></i> Event Cal</a>
        <a href="/personalcal" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-calendar"></i> Personal Cal</a>
        <a href="/tasklist" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-list-ul"></i> Task List</a>
        <a href="/profile" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-user"></i> Profile</a>
        <a href= "/logout" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-sign-out"></i> Logout</a>
        {% else %}
        <a href="/login" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-user"></i> Login</a>
        <a href="/register" class="w3-bar-item w3-button" style= "color:#bbbbbb"><i class="fa fa-user-plus"></i> Register</a>
        {% endif %}
        
        
        
      </div>
    </div>
  </div>
  
      <main role="main">
          <div class="container">
            {% if messages %}
              {% for message in messages %}
                <div class = "alert alert-{{ message.tags }}"> 
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
      </main>
      <br></br>
      <br></br>
    <!-- jQuery, Popper.js, Bootstrap JS -->
     <!-- Might be able to delete research more bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

STAJJ/cockycal/templates/cockycal/eventcal.html
{% extends "cockycal/base.html" %}
    {% block content %}
    <h1>Event Calendar Page</h1>
{% endblock content %}

STAJJ/cockycal/templates/cockycal/home.html
{% extends "cockycal/base.html" %}

{% block styles %}
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
  }
  
  .profile {
    display: flex;
    align-items: center;
    padding: 20px;
  }
  .custom-row {
    display: flex;
    flex-direction: row;
    align-items: flex-end;
  }
  .profile img {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    margin-right: 15px;
  }

  table {
    width: 100%;
    border-collapse: collapse;
  }

  th, td {
    border: 1px solid black;
    padding: 8px;
    text-align: left;
  }

  th {
    background-color: #f2f2f2;
  }

    button {
    background-color: #73000a;
    }
    .custom-btn:hover {
    background-color: #000000;
    transition: 0.3s;
    }

</style>
{% endblock %}

{% block content %}
<div class="container">
    <br>
    <br>
    <br>
    
    <h1 class="text-5xl font-bold text-gray-900 pl-5">Welcome {{ user.username }}</h1>        
        
    </div>
    <br>
    <br>
    <div class="row custom-row">
        <div class="col-md-6">
            <h1 class="text-3xl text-gray-900 pl-5">7-Day Weather Forecast:</h1>
            {% if weather_forecast %}   
            <table class="table table-bordered" cellspacing="30" cellpadding="5">
                <thead>
                    <tr>
                        <th>Date,</th>
                        <th>Day Temp,</th>
                        <th>Night Temp,</th>
                        <th>Description</th>
                    </tr>
                </thead>
                {% for date in weather_forecast %}
                    <tr>
                        <td>{{ date.date }}</td>
                        <td>{{ date.temp_high }}°F</td>
                        <td>{{ date.temp_low }}°F</td>
                        <td>{{ date.description }} <img src = "http://openweathermap.org/img/w/{{ date.icon }}.png" alt="Image Not Available."/></td>
                    </tr>
                {% endfor %}
            </table>    
            {% endif %}   
        </div>
        <div class="col-md-6">
            {% if upcoming %}
            <h2 class="text-3xl text-gray-900 pl-5">Upcoming Events:</h2>
            <form id="eventForm" method="post" action="{% url 'cockycal-home' %}">
                {% csrf_token %}                
                <table class="table table-bordered" cellspacing="30" cellpadding="5">
                    <thead>
                        <tr>
                            <th>Remove</th>
                            <th>Title</th>
                            <th>Start Time</th>
                            <th>End Time</th>
                            <th>Location</th>
                        </tr>
                    </thead>
                    {% for event in upcoming %}
                        <tr>
                            <td><input type = "checkbox" name="delete_event" value="{{ event.id }}"></td>
                            <td>
                                <a href="{% url 'cal:event_details' event_id=event.id %}">{{ event.title }}</a>
                            </td>
                            <td>{{ event.start_time}}</td>
                            <td>{{ event.end_time }}</td>
                            <td>{{ event.location }} </td>
                        </tr>
                    {% endfor %}
                </table>
                <br><button type="submit" style="background-color:#73000a; color:#fff" class="btn btn-primary custom-btn"> Remove Selected Events</button><br><br><br>   
            </form>
            {% else %}
            <h2 class="text-3xl text-gray-900 pl-5">Add an event to your personal calendar to view your upcoming events!</h2><br><br><br><br><br>
            {% endif %}
            {% if tasks %}
            <h2 class="text-3xl text-gray-900 pl-5">Upcoming Tasks:</h2>
            <form id="taskForm" method="post" action="{% url 'cockycal-home' %}">
                {% csrf_token %}     
                <table class="table table-bordered" cellspacing="30" cellpadding="5">
                    <thead>
                        <tr>
                            <th>Completed</th>
                            <th>Title</th>
                            <th>Due Date</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    {% for task in tasks %}
                        <tr>
                            <td><input type = "checkbox" name="task_completed" value="{{ task.pk }}"></td>
                            <td>{{ task.title }}</td>
                            <td>{{ task.due_date }}</td>
                            <td>{{ task.description }}</td>
                        </tr>
                    {% endfor %}
                </table>
            <br><button type="submit" style="background-color:#73000a; color:#fff" class="btn btn-primary custom-btn"> Remove Selected Tasks</button><br><br><br>   
        </form>
            {% else %} 
            <br><br><br><br><br><br>
            <h1 class="text-3xl text-gray-900 pl-5">Create a Task to view your upcoming tasks!</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

STAJJ/cockycal/templates/cockycal/profile.html
<!--this page contains the html for the profile page -->
{% extends "cockycal/base.html" %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
{% block content %}
    {% if user.is_authenticated %}
    <br>
    <br>
    <br>
    <!--about me container by sarah carlucci -->
    <div class="content-section pl-5">
      <h1 class="text-5xl text-gray-900 pb-5">{{ user.username }}</h1>
      <div class="media">
        
        <div class="media-body">
          <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
          </div>
          <!--displays the users information-->
          <h2 class="account-heading">About Me </h2>
          <p class="text-secondary py-2">{{ user.email }}</p>
          <label for="name">Name: {{ user.profile.name }}</label><br>
          <label for="name">Occupation: {{ user.profile.occupation }}</label><br>
          <label for="name">Birthday: {{ user.profile.birthday }}</label><br>
          <label for="name">Phone Number: {{ user.profile.phonenumber }}</label><br>
        </div>
      </div>
   </div>

   <!--form to update user's profile info information-->
   <!--updates info on screen after -->
    <div class="content-section pl-5">
      <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <legend class = "border-bottom mb-4">Update Your Profile Info Here! </legend>  
        <fieldset class = "form-group">
            {{ p_form|crispy}}
        </fieldset>
        
        <div class = "form-group">
          
            <button class = "btn btn-outline-info" type ="submit">Update </button>
        </div>
    </form>
    </div>
    <!-- displays the users upcoming events for the week-->
    <div class="pl-5">
      {% if weekly %}
      <h5>This Weeks Events:</h5>             
      <table class="table table-bordered" cellspacing="30" cellpadding="5">
          <thead>
              <tr>
                  <th>Title</th>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th>Location</th>
              </tr>
          </thead>
          {% for event in weekly %}
              <tr>
                  <td>
                      <a href="{% url 'cal:event_details' event_id=event.id %}">{{ event.title }}</a>
                  </td>
                  <td>{{ event.start_time}}</td>
                  <td>{{ event.end_time }}</td>
                  <td>{{ event.location }} </td>
              </tr>
          {% endfor %}
      </table>
      {% else %}
      <h2>Events occuring in the next 7 days will show here!</h2>
      {% endif %}
      <br><br><br>
    </div>

    {% else %}
    <h2>To View Calendar Features, Login Below  </h2>
      <div class ="border-top pt-3">
        <small class = "text-muted"> 
             <a href="/">Login</a>
        </small>
      </div>
    {% endif %}
{% endblock content %}
{% endif %}